---
meta:
  network: cf1
  subdomain: (( merge || "admin" )
  aws:
    availability_zone: ~
    availability_zone2: ~
  admin_ui_uaa_client:
    id: (( merge || "admin-ui" ))
    secret: (( merge ))

name: admin-ui
director_uuid: (( merge ))
releases:
  - name: admin-ui
    version: latest
  - name: collectd
    version: latest
  - name: fisma
    version: latest
  - name: tripwire
    version: latest
  - name: clamav
    version: latest
  - name: riemannc
    version: latest
  - name: awslogs
    version: latest
  - name: nessus-agent
    version: latest
  - name: newrelic
    version: latest
compilation: (( merge ))
update: (( merge ))
networks: (( merge ))

resource_pools:
- name: medium_z1
  availability_zone: (( meta.aws.availability_zone ))
  network: (( meta.network ))
  stemcell: (( merge ))
  cloud_properties: (( merge ))

disk_pools:
- name: admin-ui
  availability_zone: (( meta.aws.availability_zone ))
  disk_size: 5_120
  cloud_properties:
    encrypted: true

jobs:
- name: admin_ui
  templates:
    - name: admin_ui
      release: admin-ui
    - name: collectd
      release: collectd
    - name: harden
      release: fisma
    - name: tripwire
      release: tripwire
    - name: clamav
      release: clamav
    - name: riemannc
      release: riemannc
    - name: awslogs
      release: awslogs
    - name: nessus-agent
      release: nessus-agent
    - name: newrelic-monitor
      release: newrelic
  instances: 1
  resource_pool: medium_z1
  persistent_disk_pool: admin-ui
  networks:
    - name: (( meta.network ))
      type: dynamic

- name: register_admin_ui
  templates:
    - name: register_admin_ui
      release: admin-ui
  instances: 1
  resource_pool: medium_z1
  lifecycle: errand
  networks:
    - name: (( meta.network ))

- name: deregister_admin_ui
  templates:
    - name: deregister_admin_ui
      release: admin-ui
  instances: 1
  resource_pool: medium_z1
  lifecycle: errand
  networks:
    - name: (( meta.network ))

properties:
  cc:
    srv_api_uri: (( merge ))
  system_domain: (( merge ))
  uaa:
    url: (( merge ))
    admin:
      client_secret: (( merge ))
  tripwire: (( merge ))
  awslogs: (( merge ))
  nessus-agent: (( merge ))
  newrelic: (( merge ))
  collectd:
    riemann_server: (( merge ))
    hostname_prefix: (( merge ))

  riemann:
    server: (( properties.collectd.riemann_server ))
    port: 5555
  admin_ui:
    cloud_controller_uri: (( properties.cc.srv_api_uri ))
    cloud_controller_ssl_verify_none: (( properties.ssl.skip_cert_verify ))
    uri: (( meta.subdomain "." properties.system_domain ))
    users: ~
    admins: (( merge ))
    uaa:
      url: (( properties.uaa.url ))
      admin_client_secret: (( properties.uaa.admin.client_secret ))
      client:
        id: (( meta.admin_ui_uaa_client.id ))
        secret: (( meta.admin_ui_uaa_client.secret ))
      scopes:
        admin: ~
        user: ~

    ccdb:
      scheme: (( databases.db_scheme ))
      address: (( databases.address ))
      port: (( databases.port ))
      username: (( databases.roles.ccadmin.username ))
      password: (( databases.roles.ccadmin.password ))
      database: ccdb
    uaadb:
      scheme: (( databases.db_scheme ))
      address: (( databases.address ))
      port: (( databases.port ))
      username: (( databases.roles.uaaadmin.username ))
      password: (( databases.roles.uaaadmin.password ))
      database: uaadb

  ssl:
    skip_cert_verify: (( merge || false ))
  networks:
    apps: (( meta.network ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
    address: (( machines.[0] ))
  databases:
    db_scheme: (( merge ))
    address: (( merge ))
    port: (( merge ))
    roles: (( merge ))
